version: "3"
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 9004:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9003:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  db:
    image: mariadb:10
    ports:
      - 9002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234abcd
      - MYSQL_DATABASE=test
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    image: ucsp/event-api:latest
    ports:
      - 9001:8080
    depends_on:
      - db

  logger:
    image: ucsp/event-logger:latest
    depends_on:
      - db
      - kafka

