version: "3"
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  db:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=1234abcd
      - MYSQL_DATABASE=test
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    image: ucsp/event-api:latest
    ports:
      - 8080:8081
    depends_on:
      - db

  logger:
    image: ucsp/event-logger:latest
    depends_on:
      - db
      - kafka

  forwarder:
    image: ucsp/event-forwarder:latest
    depends_on:
      - db
      - kafka

  generator:
    image: ucsp/event-generator:latest
    depends_on:
      - kafka

