spring:
  datasource:
    druid:
      url: jdbc:mysql://db:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
      username: root
      password: 1234abcd

  # Kafka servers
  kafka:
    bootstrap-servers: kafka:9092

internal-api:
  app-msg:
    url: http://192.168.5.103:9093/
  web-msg:
    url: http://192.168.5.103:9093/

