spring:
  datasource:
    druid:
      url: jdbc:mysql://db:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 1234abcd
